In [1]:
import matplotlib
matplotlib.use('Agg') # サーバーでx環境がない場合などはこれがないとmatplotlibが動かない
import pygrib
import matplotlib.pyplot as plt
import numpy as np
import math
from mpl_toolkits.basemap import Basemap

In [2]:
grbs = pygrib.open('/Users/k-ikegami/Desktop/GRIB/Z__C_RJTD_20170120090000_MSM_GPV_Rjp_L-pall_FH00-15_grib2.bin')

In [35]:
grbs(name = "Relative humidity")

[6:Relative humidity:% (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900,
 12:Relative humidity:% (instant):regular_ll:isobaricInhPa:level 97500.0 Pa:fcst time 0 hrs:from 201701200900,
 18:Relative humidity:% (instant):regular_ll:isobaricInhPa:level 95000.0 Pa:fcst time 0 hrs:from 201701200900,
 24:Relative humidity:% (instant):regular_ll:isobaricInhPa:level 92500.0 Pa:fcst time 0 hrs:from 201701200900,
 30:Relative humidity:% (instant):regular_ll:isobaricInhPa:level 90000.0 Pa:fcst time 0 hrs:from 201701200900,
 36:Relative humidity:% (instant):regular_ll:isobaricInhPa:level 85000.0 Pa:fcst time 0 hrs:from 201701200900,
 42:Relative humidity:% (instant):regular_ll:isobaricInhPa:level 80000.0 Pa:fcst time 0 hrs:from 201701200900,
 48:Relative humidity:% (instant):regular_ll:isobaricInhPa:level 70000.0 Pa:fcst time 0 hrs:from 201701200900,
 54:Relative humidity:% (instant):regular_ll:isobaricInhPa:level 60000.0 Pa:fcst time 0 hrs:from 201701200900,
 

In [31]:
for grb in grbs:
    print(grb)

1:Geopotential Height:gpm (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900
2:U component of wind:m s**-1 (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900
3:V component of wind:m s**-1 (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900
4:Temperature:K (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900
5:Vertical velocity:Pa s**-1 (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900
6:Relative humidity:% (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900
7:Geopotential Height:gpm (instant):regular_ll:isobaricInhPa:level 97500.0 Pa:fcst time 0 hrs:from 201701200900
8:U component of wind:m s**-1 (instant):regular_ll:isobaricInhPa:level 97500.0 Pa:fcst time 0 hrs:from 201701200900
9:V component of wind:m s**-1 (instant):regular_ll:isobaricInhPa:level 97500.0 Pa:fcst time 0 hrs

In [34]:
# forecastTimeを一つ選ぶと、物理量ごとに値が得られる。例えばindex=0は海面更生気圧
# その物理量ごとに各地点での値が入っている
grb = grbs.select(forecastTime=0)[0]

In [17]:
lats, lons = grb.latlons()

In [22]:
np.shape(lats)

(253, 241)

In [23]:
np.shape(lons)

(253, 241)

In [24]:
lats

array([[ 47.6,  47.6,  47.6, ...,  47.6,  47.6,  47.6],
       [ 47.5,  47.5,  47.5, ...,  47.5,  47.5,  47.5],
       [ 47.4,  47.4,  47.4, ...,  47.4,  47.4,  47.4],
       ..., 
       [ 22.6,  22.6,  22.6, ...,  22.6,  22.6,  22.6],
       [ 22.5,  22.5,  22.5, ...,  22.5,  22.5,  22.5],
       [ 22.4,  22.4,  22.4, ...,  22.4,  22.4,  22.4]])

In [25]:
lons

array([[ 120.   ,  120.125,  120.25 , ...,  149.75 ,  149.875,  150.   ],
       [ 120.   ,  120.125,  120.25 , ...,  149.75 ,  149.875,  150.   ],
       [ 120.   ,  120.125,  120.25 , ...,  149.75 ,  149.875,  150.   ],
       ..., 
       [ 120.   ,  120.125,  120.25 , ...,  149.75 ,  149.875,  150.   ],
       [ 120.   ,  120.125,  120.25 , ...,  149.75 ,  149.875,  150.   ],
       [ 120.   ,  120.125,  120.25 , ...,  149.75 ,  149.875,  150.   ]])

In [26]:
# ６０９７３地点のデータ
lats.size

60973

In [18]:
# grb["values"]でも同じ
mslp = grb.values

In [28]:
mslp

array([[ 225.37739468,  225.50239468,  225.50239468, ...,  117.87739468,
         117.00239468,  116.12739468],
       [ 224.62739468,  224.50239468,  224.25239468, ...,  117.62739468,
         116.75239468,  115.87739468],
       [ 224.00239468,  223.50239468,  223.50239468, ...,  117.37739468,
         116.50239468,  115.62739468],
       ..., 
       [ 171.25239468,  170.00239468,  168.50239468, ...,  155.25239468,
         155.62739468,  155.75239468],
       [ 171.37739468,  170.12739468,  168.87739468, ...,  155.12739468,
         155.37739468,  155.50239468],
       [ 171.50239468,  170.25239468,  169.25239468, ...,  154.87739468,
         155.00239468,  155.00239468]])

In [27]:
# 先の各地点に対して値が得られている
mslp.size

60973

In [30]:
# draw
levels = range(math.floor(mslp.min()/100)*100, math.ceil(mslp.max()/100)*100+1,200)

# lat,lonを一次元に変換
# 何故か二次元のままでは描画できない
flat_lats= np.ravel(lats)
flat_lons= np.ravel(lons)

fig = plt.figure()

# マップを作成。4つのパラメータは描画する範囲の指定
m = Basemap(llcrnrlat=lats.min(),urcrnrlat=lats.max(), llcrnrlon=lons.min(),urcrnrlon=lons.max())

# 等圧線をひく
m.contour(flat_lons, flat_lats,mslp,latlon=True,tri=True,levels=levels)

# 海岸線をひく
m.drawcoastlines() 

fig.savefig('/Users/k-ikegami/Desktop/GRIB/mslp.png')

/Users/k-ikegami/anaconda/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:3505: MatplotlibDeprecationWarning: The ishold function was deprecated in version 2.0.
  b = ax.ishold()
/Users/k-ikegami/anaconda/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:3572: MatplotlibDeprecationWarning: axes.hold is deprecated.
    See the API Changes document (http://matplotlib.org/api/api_changes.html)
    for more details.
  ax.hold(b)
