In [45]:
import pygrib
import numpy as np
grbs = pygrib.open('/Users/k-ikegami/Desktop/GRIB/Z__C_RJTD_20170120090000_MSM_GPV_Rjp_L-pall_FH00-15_grib2.bin')

In [21]:
# 時間
time_list = list(set([grb.forecastTime for grb in grbs]))

In [30]:
time_list

[0, 3, 6, 9, 12, 15]

In [29]:
# 空間
# 空間は時間を通じて一定？物理量に対して一定？
for i in grbs.select(forecastTime=0):
    lats , lons = i.latlons()
    print(np.shape(lats))

(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)

In [31]:
for i in grbs.select(forecastTime=3):
    lats , lons = i.latlons()
    print(np.shape(lats))

(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)
(253, 241)

時間に対しても物理量に対しても一定っぽい

In [32]:
# 一番上の物理量からlats, lonsを得る
# num_row, num_colだけあればいい
sample = grbs.select(forecastTime=0)[0]
lats, lons = sample.latlons()

In [33]:
lats

array([[ 47.6,  47.6,  47.6, ...,  47.6,  47.6,  47.6],
       [ 47.5,  47.5,  47.5, ...,  47.5,  47.5,  47.5],
       [ 47.4,  47.4,  47.4, ...,  47.4,  47.4,  47.4],
       ..., 
       [ 22.6,  22.6,  22.6, ...,  22.6,  22.6,  22.6],
       [ 22.5,  22.5,  22.5, ...,  22.5,  22.5,  22.5],
       [ 22.4,  22.4,  22.4, ...,  22.4,  22.4,  22.4]])

In [51]:
lats[:,0]

array([ 47.6,  47.5,  47.4,  47.3,  47.2,  47.1,  47. ,  46.9,  46.8,
        46.7,  46.6,  46.5,  46.4,  46.3,  46.2,  46.1,  46. ,  45.9,
        45.8,  45.7,  45.6,  45.5,  45.4,  45.3,  45.2,  45.1,  45. ,
        44.9,  44.8,  44.7,  44.6,  44.5,  44.4,  44.3,  44.2,  44.1,
        44. ,  43.9,  43.8,  43.7,  43.6,  43.5,  43.4,  43.3,  43.2,
        43.1,  43. ,  42.9,  42.8,  42.7,  42.6,  42.5,  42.4,  42.3,
        42.2,  42.1,  42. ,  41.9,  41.8,  41.7,  41.6,  41.5,  41.4,
        41.3,  41.2,  41.1,  41. ,  40.9,  40.8,  40.7,  40.6,  40.5,
        40.4,  40.3,  40.2,  40.1,  40. ,  39.9,  39.8,  39.7,  39.6,
        39.5,  39.4,  39.3,  39.2,  39.1,  39. ,  38.9,  38.8,  38.7,
        38.6,  38.5,  38.4,  38.3,  38.2,  38.1,  38. ,  37.9,  37.8,
        37.7,  37.6,  37.5,  37.4,  37.3,  37.2,  37.1,  37. ,  36.9,
        36.8,  36.7,  36.6,  36.5,  36.4,  36.3,  36.2,  36.1,  36. ,
        35.9,  35.8,  35.7,  35.6,  35.5,  35.4,  35.3,  35.2,  35.1,
        35. ,  34.9,

In [34]:
lons

array([[ 120.   ,  120.125,  120.25 , ...,  149.75 ,  149.875,  150.   ],
       [ 120.   ,  120.125,  120.25 , ...,  149.75 ,  149.875,  150.   ],
       [ 120.   ,  120.125,  120.25 , ...,  149.75 ,  149.875,  150.   ],
       ..., 
       [ 120.   ,  120.125,  120.25 , ...,  149.75 ,  149.875,  150.   ],
       [ 120.   ,  120.125,  120.25 , ...,  149.75 ,  149.875,  150.   ],
       [ 120.   ,  120.125,  120.25 , ...,  149.75 ,  149.875,  150.   ]])

In [36]:
num_row = np.shape(lats)[0]
num_col = np.shape(lats)[1]

In [38]:
# 以上を一回関数にする
def time_list(grbs):
    time_list = list(set([grb.forecastTime for grb in grbs]))
    return time_list

def point_list(grbs):
    sample = grbs.select(forecastTime=0)[0]
    lats, lons = sample.latlons()
    return lats, lons

In [43]:
# gribでのoutputが出せるか？
from ncepgrib2 import Grib2Encode

In [ ]:
# times はinteger list
# lat_pointsはlatitudeを指定するnumpy array
# lon_pointsはlongtitudeを指定するnumpy array

def separation(grbs, times, lat_points, lon_points):
    # separate by forecastTime
    time_index = time_list(grbs)
    lats, lons = point_list(grbs)[0], point_list(grbs)[1]
    
    used_lats = list(set(lats[:, 0]).intersection(set(lat_points)))
    used_lons = list(set(lons[0, :]).intersection(set(lon_points)))
    used_times = list(set(time_index).intersection(set(times)))
    
    # lats, lonsのindexを取ってくる
    initial_lat = lats[0,0]
    iitial_lon = lons[0,0]
    lats_index = [(initial_lat - i)/0.1 for i in used_lats]
    lons_index = [(i - initial_lon)/0.125 for i in used_lons]
    
    if used_times = []:
        print("Use correct times")
        
    elif used_lats = []:
        print("Use correct latitudes")
        
    elif used_lons = []:
        print("Use correct longtitudes")
        
    # とりあえずvalueを取ってくる
    # GRIBにencodeすればいい
    else:
        for time in time_index:
            selected_grb = grbs.select(forecastTime = time)
            for grb in selected_grbs:
                grb.values[lats_index, lons_index]

In [64]:
# これは、最初の物理量のある時間における全てのポイントでの観測値
grbs.select(forecastTime = 0)[1].values

array([[-0.31599617,  0.55900383,  0.51212883, ...,  0.30900383,
         0.04337883, -0.25349617],
       [-0.58162117,  0.09025383, -0.19099617, ...,  0.30900383,
         0.13712883, -0.19099617],
       [-0.58162117, -0.56599617, -0.65974617, ...,  0.27775383,
         0.13712883, -0.03474617],
       ..., 
       [-1.03474617,  0.13712883,  1.07462883, ..., -1.33162117,
        -1.31599617, -1.34724617],
       [-0.75349617,  0.48087883,  1.49650383, ..., -1.36287117,
        -1.40974617, -1.50349617],
       [-0.47224617,  0.71525383,  1.80900383, ..., -1.42537117,
        -1.58162117, -1.73787117]])

In [65]:
grbs.select(forecastTime = 0, 3)

SyntaxError: positional argument follows keyword argument (<ipython-input-65-663678d3fa1e>, line 1)

In [55]:
print(grbs.messages)

552


In [57]:
for grb in grbs:
    print(grb)

1:Geopotential Height:gpm (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900
2:U component of wind:m s**-1 (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900
3:V component of wind:m s**-1 (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900
4:Temperature:K (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900
5:Vertical velocity:Pa s**-1 (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900
6:Relative humidity:% (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900
7:Geopotential Height:gpm (instant):regular_ll:isobaricInhPa:level 97500.0 Pa:fcst time 0 hrs:from 201701200900
8:U component of wind:m s**-1 (instant):regular_ll:isobaricInhPa:level 97500.0 Pa:fcst time 0 hrs:from 201701200900
9:V component of wind:m s**-1 (instant):regular_ll:isobaricInhPa:level 97500.0 Pa:fcst time 0 hrs

In [60]:
grbs[1]

1:Geopotential Height:gpm (instant):regular_ll:isobaricInhPa:level 100000.0 Pa:fcst time 0 hrs:from 201701200900